### Root
GET http://localhost:4000

### Error
GET http://localhost:4000/some_routeasdad

### Protected
GET http://localhost:4000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTAxNTY2NzAsImV4cCI6MTYxMDE1NjcwMCwiYXVkIjoiNWZmOTBhN2UyM2NiODQzMGIxYmVkNzgxIiwiaXNzIjoianF1aW5jbC5jb20ifQ.11ZCIexB_pW0eXvqYwxbblrf7WgtdUjQdo4kysu7zco


### Auth Register
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "email": "jcardenas.lie@gmail.com",
  "password": "1234"
}

### Auth Login
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "jcardenas.lie@gmail.com",
  "password": "1234"
}


### Auth Refresh Token
POST http://localhost:4000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTAxNTY2NzAsImV4cCI6MTY0MTcxNDI3MCwiYXVkIjoiNWZmOTBhN2UyM2NiODQzMGIxYmVkNzgxIiwiaXNzIjoianF1aW5jbC5jb20ifQ.4ToQtf1zT1XRXWzgk7JLOCFQuZrU-Ki83Zoj27ojFoU"
}

### Auth Logout
DELETE http://localhost:4000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDkxMDIwMTUsImV4cCI6MTY0MDY1OTYxNSwiYXVkIjoiNWZlOGYyYWU4Y2EwMzQ5ZGNjZWJlODYzIiwiaXNzIjoianF1aW5jbC5jb20ifQ.z4SEImVx8M9vNekZBBW5ziWaH6oufSB1Zkhs-IRg2j8"
}

